[project]
name = "db_repo"
version = "1.0.0"
description = "A client for interacting with databases. Currently supports SQLite3."

[tool.pytest.ini_options]
pythonpath = [
  "."
]

[build-system]
requires = ["flit_core<4"]
build-backend = "flit_core.buildapi"